name: get_patterm_demo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^4.2.1
  get: 4.3.8
  dio: 4.0.0
  intl: 0.17.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/models/
  uses-material-design: true

